### PR TITLE
Update to 1.2.1

### PR DESCRIPTION
**Pull request by anjakefala**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by anjakefala** [comment]
@conda-forge-admin, please rerender

**Comment by cbrueffer** [comment]
@anjakefala No packages have built from this update, any idea what's up? See `https://anaconda.org/conda-forge/visidata/files`

**Comment by anjakefala** [comment]
@cbrueffer Oh blech.

I am unsure why it did not work, but I will look into it now.

**Comment by anjakefala** [comment]
Thanks for bringing it to my attention! =)

**Comment by cbrueffer** [comment]
Thanks for looking into it! Strange, when I rerender locally I get the right configs. Maybe something's up with the web service?

**Comment by anjakefala** [comment]
Oy! Nice catch.

Maybe that is it. I will open an issue with them. 

If possible, could you please be able to make a fork and PR with the right configs for now?

**Comment by anjakefala** [comment]
You would just need to add this https://github.com/conda-forge/visidata-feedstock/pull/3/commits/4ecf253972acd6b02454e315e1c6bffa217353b3

to the recipes/meta.yml

**Comment by cbrueffer** [comment]
Sure thing!

**Comment by anjakefala** [comment]
:1st_place_medal: :100: :smile:

**Pull request merged**
