### PR TITLE
Rerender and rebuild.

### PR DESCRIPTION
**Pull request by cbrueffer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by anjakefala** [comment]
Hm.It still seems to have left the building disabled. 

I will merge this in to check and then possibly message someone for help.

Thanks for all of your help! :bowing_woman:

**Comment by cbrueffer** [comment]
It was an intermittent smithy issue, I have the correct revision locally now.

**Comment by anjakefala** [comment]
:+1:

**Comment by cbrueffer** [comment]
Something is really strange, now it's not working again :-/

**Comment by cbrueffer** [comment]
I'll keep trying and will send a new PR when things start working again. Thanks for your time!

**Comment by anjakefala** [comment]
Thank you too! :bowing_woman: 

This is good impetus to set up a conda-smithy environment. ^^;

**Comment by cbrueffer** [comment]
Working now, #5 ! Indeed, I find the local rerendering more convenient. First time I've seen issues like this though.

**Pull request merged**
